import 'package:stylish_app/core/models/product_model.dart';

// Data from Trending Products and Search Page
const List<ProductStore> trendingProductsList = [
  ProductStore(
    image: 'assets/images/watch.png',
    name: "IWC Schaffhausen",
    description: "2021 Pilot's Watch \"SIHH 2019\" 44mm",
    price: "₹650",
    oldPrice: "₹1599",
    discount: "50% off",
    rating: 5,
    reviewCount: 650,
  ),
  ProductStore(
    image: 'assets/images/whiteshoes.png',
    name: "Labbin White Sneakers",
    description: "For Men and Female",
    price: "₹650",
    oldPrice: "₹1250",
    discount: "50% off",
    rating: 4,
    reviewCount: 650,
  ),
  ProductStore(
    image: 'assets/images/womenshandback.png',
    name: "Mammon Women's Handbag",
    description: "(Set of 3, Beige)",
    price: "₹750",
    oldPrice: "₹1999",
    discount: "50% off",
    rating: 4,
    reviewCount: 750,
  ),
  ProductStore(
    image: 'assets/images/sandalcoklat.png',
    name: "Do Bhai Women Wedges Sandal",
    description: "(Butterfly)",
    price: "₹750",
    oldPrice: "₹1499",
    discount: "50% off",
    rating: 4,
    reviewCount: 750,
  ),
  ProductStore(
    image: 'assets/images/lipstik.png',
    name: "Lakme Enrich Matte Lipstick",
    description: "Shade RM1(4.7gm)",
    price: "₹950",
    oldPrice: "₹1990",
    discount: "50% off",
    rating: 4,
    reviewCount: 950,
  ),
  ProductStore(
    image: 'assets/images/jordan.png',
    name: "Nike Air Jordan",
    description: "Nike Air Jordan 1 Retro High OG",
    price: "₹1250",
    oldPrice: "₹2500",
    discount: "50% off",
    rating: 5,
    reviewCount: 120,
  ),
];

// Data from Deal Of Day
const List<ProductStore> dealOfDayProductsList = [
  Product(
    image: 'assets/images/womenprintedkurta.png',
    name: "Women Printed Kurta",
    description: "Neque porro quisquam est qui dolorem ipsum quia",
    price: "₹1500",
    oldPrice: "₹2499",
    discount: "30% Off",
    rating: 4,
    reviewCount: 56890,
  ),
  Product(
    image: 'assets/images/HRX.png',
    name: "HRX by Hrithik Roshan",
    description: "Neque porro quisquam est qui dolorem ipsum quia",
    price: "₹2499",
    oldPrice: "₹4999",
    discount: "50% Off",
    rating: 4,
    reviewCount: 344567,
  ),
  Product(
    image: 'assets/images/philips.png',
    name: "Philips BHH880/10",
    description:
        "Hair Straightening Brush With Keratin Infused Bristles (Black).",
    price: "₹999",
    oldPrice: "₹1999",
    discount: "50% Off",
    rating: 4,
    reviewCount: 646776,
  ),
  Product(
    image: 'assets/images/titan.png',
    name: "TITAN Men Watch- 1806N",
    description:
        "This Titan watch in Black color is I wanted to buy for a long time",
    price: "₹1500",
    oldPrice: "₹3500",
    discount: "50% Off",
    rating: 5,
    reviewCount: 15007,
  ),
  Product(
    image: 'assets/images/flatandheels.png',
    name: "Red High Heels",
    description: "Elegant red high heels for evening wear",
    price: "₹1299",
    oldPrice: "₹2999",
    discount: "50% Off",
    rating: 4,
    reviewCount: 450,
  ),
  Product(
    image: 'assets/images/hotsummersale.png',
    name: "Summer Floral Dress",
    description: "Light and breezy floral dress for summer",
    price: "₹899",
    oldPrice: "₹1599",
    discount: "30% Off",
    rating: 4,
    reviewCount: 320,
  ),
  Product(
    image: 'assets/images/mansstarry.png',
    name: "Designer Face Masks",
    description: "Set of 3 cotton face masks",
    price: "₹299",
    oldPrice: "₹599",
    discount: "50% Off",
    rating: 4,
    reviewCount: 1200,
  ),
  Product(
    image: 'assets/images/blackwinter.png',
    name: "Black Winter Jacket",
    description: "Warm and stylish winter jacket",
    price: "₹2499",
    oldPrice: "₹4999",
    discount: "50% Off",
    rating: 5,
    reviewCount: 890,
  ),
];

// Data from Wishlist Page
const List<Product> wishlistProductsList = [
  Product(
    image: "assets/images/blackwinter.png",
    name: "Black Winter...",
    description: "Autumn And Winter Casual cotton-padded jacket...",
    price: "₹499",
    oldPrice: "₹999",
    discount: "50% OFF",
    rating: 4,
    reviewCount: 6890,
    height: 200.0,
  ),
  Product(
    image: "assets/images/mansstarry.png",
    name: "Mens Starry",
    description: "Mens Starry Sky Printed Shirt 100% Cotton Fabric",
    price: "₹399",
    oldPrice: "₹799",
    discount: "50% OFF",
    rating: 4,
    reviewCount: 152344,
    height: 240.0,
  ),
  Product(
    image: "assets/images/blackdress.png",
    name: "Black Dress",
    description: "Solid Black Dress for Women, Sexy Chain Shorts Ladi...",
    price: "₹2,000",
    oldPrice: "₹4,000",
    discount: "50% OFF",
    rating: 5,
    reviewCount: 523456,
    height: 260.0,
  ),
  Product(
    image: "assets/images/pinkembroid.png",
    name: "Pink Ambroide...",
    description: "EARTHEN Rose Pink Embroidered Tiered Max...",
    price: "₹1,900",
    oldPrice: "₹3,800",
    discount: "50% OFF",
    rating: 4,
    reviewCount: 45678,
    height: 220.0,
  ),
  Product(
    image: "assets/images/flaredress.png",
    name: "Flare Dress",
    description: "Antheaa Black & Rust Orange Floral Print Tiered Midi F...",
    price: "₹1,990",
    oldPrice: "₹3,980",
    discount: "50% OFF",
    rating: 3,
    reviewCount: 335566,
    height: 240.0,
  ),
  Product(
    image: "assets/images/denimdress.png",
    name: "denim dress",
    description: "Blue cotton denim dress Look 2 Printed cotton dr...",
    price: "₹999",
    oldPrice: "₹1,999",
    discount: "50% OFF",
    rating: 4,
    reviewCount: 21344,
    height: 210.0,
  ),
  Product(
    image: "assets/images/jordanstay.png",
    name: "Jordan Stay",
    description: "The classic Air Jordan 12 to create a shoe that's fres...",
    price: "₹4,999",
    oldPrice: "₹9,999",
    discount: "50% OFF",
    rating: 5,
    reviewCount: 1023456,
    height: 180.0,
  ),
  Product(
    image: "assets/images/realme7.png",
    name: "Realme 7",
    description: "6 GB RAM | 64 GB ROM | Expandable Upto 256...",
    price: "₹3,499",
    oldPrice: "₹6,999",
    discount: "50% OFF",
    rating: 4,
    reviewCount: 344567,
    height: 190.0,
  ),
  Product(
    image: "assets/images/ps4.png",
    name: "Sony PS4",
    description: "Sony PS4 Console, 1TB Slim with 3 Games: Gran Turis...",
    price: "₹1,999",
    oldPrice: "₹3,999",
    discount: "50% OFF",
    rating: 4,
    reviewCount: 852966,
    height: 200.0,
  ),
  Product(
    image: "assets/images/blackjacket.png",
    name: "Black Jacket 12...",
    description: "This warm and comfortable jacket is great for learni...",
    price: "₹2,999",
    oldPrice: "₹5,999",
    discount: "50% OFF",
    rating: 4,
    reviewCount: 234567,
    height: 230.0,
  ),
  Product(
    image: "assets/images/nikon.png",
    name: "D7200 Digital C...",
    description: "D7200 Digital Camera (Nikon) In New Area...",
    price: "₹26,999",
    oldPrice: "₹53,998",
    discount: "50% OFF",
    rating: 5,
    reviewCount: 67456,
    height: 190.0,
  ),
  Product(
    image: "assets/images/sepatufantopel.png",
    name: "men's & boys s...",
    description: "George Walker Derby Brown Formal Shoes",
    price: "₹999",
    oldPrice: "₹1,999",
    discount: "50% OFF",
    rating: 3,
    reviewCount: 1345678,
    height: 210.0,
  ),
];

final List<Product> allProducts = [
  ...trendingProductsList,
  ...dealOfDayProductsList,
  ...wishlistProductsList,
];
